import { CheckCircle2, Copy, Smartphone } from "lucide-react";
import type { TwoFactorSettings } from "../../types/security";
import { formatSetupKey } from "../../utils/securityForm";

type TwoFactorSetupPanelProps = {
  twoFactor: TwoFactorSettings;
  copied: boolean;
  onCopySetupKey: () => void;
};

export default function TwoFactorSetupPanel({
  twoFactor,
  copied,
  onCopySetupKey,
}: TwoFactorSetupPanelProps) {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-start">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-cyan-500 shadow-sm">
          <Smartphone size={24} strokeWidth={2.4} />
        </div>

        <div className="min-w-0 flex-1">
          <h3 className="text-xl font-black text-slate-950">
            Set up your authenticator app
          </h3>

          <p className="mt-2 max-w-2xl text-sm leading-7 text-cyan-700">
            Add a new account manually, copy the setup key, then enter the
            6-digit code generated by the app.
          </p>

          <div className="mt-4 flex flex-wrap gap-2">
            {[
              "Google Authenticator",
              "Microsoft Authenticator",
              "Authy",
              "1Password",
            ].map((app) => (
              <span
                key={app}
                className="rounded-full bg-white px-3 py-1.5 text-xs font-black text-cyan-700 shadow-sm"
              >
                {app}
              </span>
            ))}
          </div>
        </div>
      </div>

      <div className="rounded-3xl bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-extrabold uppercase tracking-wide text-slate-400">
              Setup Key
            </p>

            <p className="mt-1 text-xs font-semibold text-slate-500">
              Account: {twoFactor.issuer}: {twoFactor.account_label}
            </p>
          </div>

          <button
            type="button"
            onClick={onCopySetupKey}
            className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-xs font-extrabold shadow-sm transition ${
              copied
                ? "bg-green-500 text-white"
                : "bg-cyan-400 text-white hover:bg-cyan-500"
            }`}
          >
            {copied ? (
              <>
                <CheckCircle2 size={15} />
                Copied
              </>
            ) : (
              <>
                <Copy size={15} />
                Copy key
              </>
            )}
          </button>
        </div>

        <p className="mt-4 break-all rounded-2xl border border-slate-100 bg-slate-50 px-4 py-4 font-mono text-sm font-black tracking-wide text-slate-800">
          {formatSetupKey(twoFactor.setup_key)}
        </p>
      </div>
    </div>
  );
}